eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka


server:
  port: 8086

spring:
  application:
    name: COFIG-SERVER


#config-server with GIT
  cloud:
    config:
      server:
        git:
          uri: https://github.com/panda890/Config-server
          clone-on-start: false